## Programming Assignment 2

## These two functions are made by the sample functions 
## of makeVector and cachemean.
## Being a beginner R programmer, I started by simply
## adapting the sampe code to the Assignment2.
## It seems to be working, however...

## call example:
## 1. create matrix "x" (matrix to be inverted)
## 2. v <- makeCacheMatrix (x)
## 3. xinv <- cacheSolve (v) ("xinv" is the inverted matrix)

## makeCacheMatrix creates a list of functions
## for manipulating the "cache" in which the 
## result of the matrix inversion is stored.

makeCacheMatrix <- function(x = matrix()) {

	inv <- NULL
    set <- function(y) {
        x <<- y
		inv <<- NULL
        }
    get <- function() x
    setinv <- function(inverse) inv <<- inverse
    getinv <- function() inv
    list(set = set, get = get,
         setinv = setinv,
         getinv = getinv)
}


## use cacheSolve to calculate the inverted matrix
## it the functions generated by the makeCacheMatrix()
## to check (set/get) the content of the cache

cacheSolve <- function(x, ...) {
    inv <- x$getinv()
    if(!is.null(inv)) {
       message("getting cached data")
       return(inv)
       }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinv(inv)
    inv		
}
